### ISSUE TITLE
Pangolin episode

### ISSUE THREAD

**Issue by Czirion** [carpentries-incubator/pangenomics#38]
1) Make a reference to the discussion of terms used in the Introduction episode (not developed yet) and the relationship to the terms used by the Pangolin software.

2) Add a solution to the discussion boxes.

3) Put the description of the output graphs only at the end of the analysis using the resulting plots.

4) Exercise 1 is about the same topic as the first discussion box, maybe they could be converted into only one thing.

5) Dont show the betterlab address in the prompt

6) Describe each step. Try to homogenize the format of the description of steps with the previous episodes.

7) What is the ICL criterium?

**Comment by HaydeePeruyero** [comment]
2-7 ready

**Comment by Czirion** [comment]
Thank you!
I can take care of 1

**Comment by Czirion** [comment]
1) Consider adding the clusters made with get_homologues to the ppanggolin cluster step DONE
2) Consider tuning the clustering parameters in an exercise or talk about this in a box THIS GOES TO THE MANUAL PANGENOME EPISODE
3) Do some explanation about the result files, in the text or an exercise. DONE
4) Improve the gephi setup DONE
5) Check the final exercises DONE
6) Do something with the special analyses DONE
7) review the Gephi pictures DONE
