### ISSUE TITLE
Create a TDA introduction 

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/pangenomics#39]
Develop a theoretical introduction to tda. Episode [08-tda.md](https://github.com/paumayell/pangenomics/blob/gh-pages/_episodes/08-tda.md)
 
Thanks for contributing! :heart:

**Comment by Czirion** [comment]
In all the TDA episodes use Solution Boxes with the title: "For Mathematicians", that contain the mathematical explanations in more depth. In this way that content wont make the episodes look very long, and the mathematicians can click on the boxes to see the content.
