### ISSUE TITLE
Anvio

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/pangenomics#4]
Add some figures with the Anvio output and use them for a discussion or a challenge box.
Exercise 2 does not have a solution. Step names seem to be in title 1 (#) and no title1 size should be in a lesson. Be more descriptive with the Steps.
@shadayguerrero @Kadkam8a

**Comment by Czirion** [comment]
It would be useful to say which of the steps need more time to run.

**Comment by Czirion** [comment]
addressed in another issue
