### ISSUE TITLE
Manual Pangenome

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/pangenomics#40]
Develop episode [04-manual-pangenomes.md](https://github.com/paumayell/pangenomics/blob/gh-pages/_episodes/04-manual-pangenomes.md) to explain the two-step process, you need a distance plus a clustering algorithm to calculate pangenomes. Chose a reduced-size example that runs in live-coding, some genomes, or some gene families making sure you exemplify core/shell and cloud genome. Faa files from annotations should be used.
❤️

**Comment by HaydeePeruyero** [comment]
Extraer familias para hacer un blast pequeño. Hacer las comparaciones de todos los genes contra todos los genes.

**Comment by HaydeePeruyero** [comment]
Families with bdbh algorithm

**Comment by Czirion** [comment]
The code is ready!

- [x] Review the text of first two sections
- [x] Review the text of third section
- [x] Add an exercise

Major issue

- [ ] Consider a similarity threshold in the BDBH algorithm
