### ISSUE TITLE
practical tda-episode

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/pangenomics#41]
develope [09-tda-handson.md](https://github.com/paumayell/pangenomics/blob/gh-pages/_episodes/09-tda-handson.md) with Gudhi examples about simplex

**Comment by Czirion** [comment]
Develop a theoretical introduction to tda. Episode [08-tda.md](https://github.com/paumayell/pangenomics/blob/gh-pages/_episodes/08-tda.md)
