### ISSUE TITLE
Improve TDA episodes

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/pangenomics#42]
Develop episode [10-tda-in-pangenomes.md](https://github.com/paumayell/pangenomics/blob/gh-pages/_episodes/10-tda-in-pangenomes.md)

**Comment by shadayguerrero** [comment]
simplicial complex
simplex
examples
Filtration
ViteroisRips
check
simplicial homology
connected component betti 0
betti-holes 1

**Comment by nselem** [comment]
Create an example of a family that should connect after relaxing the parameter in a small set of families.

**Comment by HaydeePeruyero** [comment]
Falta explicar más a qué se quiere llegar con el episodio. Un poco más explícito que "apply TDA to describe Pangenomes" y ahorita eso sólo está en Questions, hay que ponerlo aquí en el texto.

**Comment by Czirion** [comment]
Discutir el significado de que haya familias que comparten genes

**Comment by nselem** [comment]
We added an episode of HGT in resistance genes and it integrates well with Pangenomic lesson
