### ISSUE TITLE
Other resources

### ISSUE THREAD

**Issue by HaydeePeruyero** [carpentries-incubator/pangenomics#44]
Check the following for other resources

SaGePhy
https://academic.oup.com/bioinformatics/article/35/18/3496/5305633

GraPPLE
https://github.com/JDHarlingLee/GraPPLE

**Comment by solnavss** [comment]
Add | OrthoVenn3: https://orthovenn3.bioinfotoolkits.net/

**Comment by solnavss** [comment]
Add | Orthology Benchmark Service: https://orthology.benchmarkservice.org

**Comment by Czirion** [comment]
Add Scoary, PanX

**Comment by solnavss** [comment]
Add | OrthoBench: http://eggnog.embl.de/orthobench/
