### ISSUE TITLE
Annotation episode

### ISSUE THREAD

**Issue by Czirion** [carpentries-incubator/pangenomics#45]
Don't delete prokka outputs

**Comment by solnavss** [comment]
Change | Exercise 1: Inspecting the GBK. Instead of doing it with the GBK use the GFF.

**Comment by solnavss** [comment]
Consideration | Make a script with the Prokka 8 minutes run. Pros: save stdin and stdout, estimate run time and use nohup or screen just in case ;)

nano prokka.sh

~~~
echo "Job started at:" && date

while read line; do prokka agalactiae_$line/*.fna --kingdom Bacteria --genus Streptococcus --species agalactiae --strain $line --usegenus --addgenes --prefix Streptococcus_agalactiae_${line}_prokka --outdir ~/pan_workshop/results/annotated/Streptococcus_agalactiae_${line}_prokka; done < TettelinList.txt

echo "Job finished successfully at:" && date
~~~

./prokka.sh 2 > prokka.err 1 > prokka.out

**Comment by Czirion** [comment]
I removed the part where we move the gbks and delete the rest.

I updated the exercise to use the gffs instead of the gbks.

**Comment by Czirion** [comment]
The subsequent episodes should update the paths to the prokka outputs that they use. @solnavss  @nselem @HaydeePeruyero @shadayguerrero

**Comment by Czirion** [comment]
Instead of making a script with prokka, use Screen when running prokka DONE
