### ISSUE TITLE
Pangolin

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/pangenomics#5]
Step names seem to be in title 1 (#) and no title1 size should be in a lesson. Be more descriptive with the Steps.
Exercise 3 does not have a solution
It would be wonderful if you can discuss a gene family that is not a core family. It would be even better if this family belongs to a BGC
@HaydeePeruyero

**Comment by Czirion** [comment]
The first three instructions have been solved
@HaydeePeruyero
