### ISSUE TITLE
Get_homologues figure and core gene familis

### ISSUE THREAD

**Issue by nselem** [carpentries-incubator/pangenomics#6]
Improve the quality of the first figure, if the figure is from the research article, maybe you can not use it unless it has a compatible-licence. Use directory instead of folder. Show an example of the gene family in the core with single-copy proteins, that if the user whish may be used for a phylogeny.
https://paumayell.github.io/pangenomics/05-get_homologues/index.html @fabel134  ? Your githbub @andrespan 
Andres why I can not see you in the editors list of this episode?

**Comment by Czirion** [comment]
addressed in another issue
